DEV_Petrov
grom4er/bank pull request #1
Opened 2021-02-28 19:05 UTC by grom4er

Create Bank application.
Add Model: User, Role.
Service: User, Role.

2021-02-28 23:38 UTC, vicire requested changes
Nice work

2021-02-28 23:38 UTC, vicire commented on .travis.yml
> +  - chmod +x mvnw
Add empty line

2021-02-28 23:38 UTC, vicire commented on src/main/java/bank/app/model/Role.java
> +public class Role {
Rename table as you made with User entity

2021-02-28 23:38 UTC, vicire commented on src/main/java/bank/app/service/UserService.java
> +    List<User> findAll();
we don't need to implement this method. On the other hand, you didn't declare and implement method `update`

2021-02-28 23:38 UTC, vicire commented on src/main/java/bank/app/service/impl/RoleServiceImpl.java
> +               .orElseThrow(() -> new UserException((
```suggestion
               .orElseThrow(() -> new NoSuchEntityException((
```
Make your exception more general. That will help you with other entities

2021-02-28 23:38 UTC, vicire commented on src/main/java/bank/app/service/impl/UserServiceImpl.java
> +                .orElseThrow(() -> new UserException("Can't find user by id " + id));
Same here

2021-03-01 16:30 UTC, vicire approved these changes

2021-03-01 17:32 UTC, boroda4436 approved these changes

2021-03-01 17:32 UTC, boroda4436 commented on pom.xml
> +                    <source>9</source>
maybe it's better to use `jdk.version` property?

2021-03-01 19:39 UTC, merged